package ss;


import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 
 * Dachely Otero Argote
 * Ernesto Alejandro Cervantes Villa
 * Jorge Alexis Rubio Sumano
 * 
 */
public class JF_GuardarReg extends javax.swing.JFrame {
    
    //private ListaUsuarios lista;
    
    /**
     * Creates new form NuevoUsuario
     */
    public JF_GuardarReg() {
        initComponents();
        this.getContentPane().setBackground(jPanel1.getBackground());
        pack();
    }
    
    /*
    public JF_GuardarReg(ListaUsuarios lista) throws IOException{
        this();
        this.lista = lista;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtIMC = new javax.swing.JLabel();
        jpIMC = new javax.swing.JTextField();
        jtTallaEdad = new javax.swing.JLabel();
        jpRangoObesidad = new javax.swing.JTextField();
        jtRangoObesidad = new javax.swing.JLabel();
        jpEscuela = new javax.swing.JTextField();
        jtEscuela = new javax.swing.JLabel();
        jpTallaEdad = new javax.swing.JPasswordField();
        jbGuardad = new javax.swing.JButton();
        jcCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Usuario");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtIMC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jtIMC.setText("IMC:");

        jpIMC.setEditable(false);
        jpIMC.setColumns(10);
        jpIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpIMCActionPerformed(evt);
            }
        });

        jtTallaEdad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jtTallaEdad.setText("Talla/Edad:");

        jpRangoObesidad.setEditable(false);
        jpRangoObesidad.setColumns(10);

        jtRangoObesidad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jtRangoObesidad.setText("Rango Obesidad:");

        jpEscuela.setColumns(10);

        jtEscuela.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jtEscuela.setText("Escuela:");

        jpTallaEdad.setEditable(false);
        jpTallaEdad.setColumns(10);

        jbGuardad.setBackground(new java.awt.Color(0, 102, 102));
        jbGuardad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jbGuardad.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardad.setText("Guardar");
        jbGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardadActionPerformed(evt);
            }
        });

        jcCancelar.setBackground(new java.awt.Color(0, 102, 102));
        jcCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jcCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jcCancelar.setText("Cancelar");
        jcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCancelarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_pequeño_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtRangoObesidad)
                    .addComponent(jtTallaEdad)
                    .addComponent(jtIMC)
                    .addComponent(jtEscuela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpRangoObesidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTallaEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEscuela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpIMC, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGuardad)
                .addGap(18, 18, 18)
                .addComponent(jcCancelar)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtTallaEdad)
                                .addComponent(jpTallaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jpIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtIMC))
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jpRangoObesidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRangoObesidad)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtEscuela)
                    .addComponent(jpEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardad)
                    .addComponent(jcCancelar))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jpIMC.getAccessibleContext().setAccessibleName("jpNombre");
        jpIMC.getAccessibleContext().setAccessibleDescription("");
        jpRangoObesidad.getAccessibleContext().setAccessibleName("jpEdad");
        jpTallaEdad.getAccessibleContext().setAccessibleName("jpApellido");

        getContentPane().add(jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpIMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpIMCActionPerformed

    private void jbGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardadActionPerformed

    }//GEN-LAST:event_jbGuardadActionPerformed

    private void jcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCancelarActionPerformed
            this.setVisible(false);
    }//GEN-LAST:event_jcCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_GuardarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_GuardarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_GuardarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_GuardarReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_GuardarReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGuardad;
    private javax.swing.JButton jcCancelar;
    private javax.swing.JTextField jpEscuela;
    private javax.swing.JTextField jpIMC;
    private javax.swing.JTextField jpRangoObesidad;
    private javax.swing.JPasswordField jpTallaEdad;
    private javax.swing.JLabel jtEscuela;
    private javax.swing.JLabel jtIMC;
    private javax.swing.JLabel jtRangoObesidad;
    private javax.swing.JLabel jtTallaEdad;
    // End of variables declaration//GEN-END:variables
}
